### ISSUE TITLE
md 文件插入script的问题

### ISSUE THREAD

**Issue by transtone** [QingWei-Li/vue-markdown-loader#1]
此md文件是否可以当做vue component被引用？

可否做成 vue-loader 的预处理 loader，在 ```<template lang='md'>#header1</template>``` 中处理markdown文件？

这里有个这样的loader，但通用性差了点： https://github.com/okoala/vue-antd-docs-loader

**Comment by QingWei-Li** [comment]
和那个不一样，我是直接把 md 文件转成 vue 组件。
写的 markdown 的内容直接转成 html，同时如果有 script 标签会被 vue-loader 处理，否则就是处理成普通的 vue template。你可以看看例子。总之作用就是方便用户用 markdown 写 vue 组件的文档，并且也能直接在文档里写 demo，可以看看视频，或者这里有具体应用。 https://github.com/mint-ui/docs/
