### ISSUE TITLE
webpack2+下使用webpack-dev-server会有多次编译的情况

### ISSUE THREAD

**Issue by jschyz** [QingWei-Li/vue-markdown-loader#14]
具体demo：
https://github.com/jschyz/vue-markdown

查到原因如下：
webpack2 使用新的 watch 文件模式，文件更变，dev-server 将会触发重编译事件
而 vue-markdown-loader 是将生成的 .vue文件生放置 _cache 文件夹处，文件发生变动，触发多次编译！

流程图如下：
![image](https://cloud.githubusercontent.com/assets/3281438/24038554/e007426e-0b3c-11e7-8059-ad58e4bdfd08.png)

**Comment by keepfool** [comment]
+1，同样出现了多次编译的问题

**Comment by 0x5e** [comment]
+1

**Comment by 0x5e** [comment]
想问一下，为什么中间产物要cache成文件然后再传给vue-loader呢？不能直接调vue-loader的函数吗？

**Comment by Tidyzq** [comment]
我在自己的fork中去除了cache，直接在内存中传递
[https://github.com/Tidyzq/vue-markdown-loader](https://github.com/Tidyzq/vue-markdown-loader)
不知道作者 @QingWei-Li  愿不愿意接受pull request呢？还是本身就希望通过cache的方式呢？

**Comment by QingWei-Li** [comment]
@Tidyzq 欢迎！因为我并不知道可以放到内存内 😂

**Comment by QingWei-Li** [comment]
fixed in `v1.0.0` 感谢 @Tidyzq
