### ISSUE TITLE
Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by alidcastano** [QingWei-Li/vue-markdown-loader#21]
I'm using vue-markdown-loader with Nuxt.js and getting the above error.

When the code is by itself it works. However, when I add even one line of markdown under it, the Vue component example renders but stops working.

Here's an example snippet: 

```js
<script>
import CoinFlip from '~components/tasks/examples/CoinFlip.vue'

export default {
  components: {
    CoinFlip
  }
}
</script>

### Coin Flip
<div class="showcase">
  <CoinFlip />
</div>

<!-- ## More text ... -->
```

Could this be due to a problem with the markdown loader? 

I opened but [an issue](https://github.com/nuxt/nuxt.js/issues/531) on Nuxt repo as well. But I have a feeling its due to the way the loader is parsing the file.

In case you need to reproduce, here's the repo: https://github.com/encyjs/encyjs.org.

**Comment by QingWei-Li** [comment]
Try upgrade this plugin version number to 1.0

**Comment by alidcastano** [comment]
Hello,

Sorry for the delay. I tried your suggestion but the problem still persists. Except now the component inside one file is turning up in all the others. Not sure if it's a change in `nuxt-generate` or the upgrade to the way your loader parses the files.

Here's the repo in case it helps: https://github.com/encyjs

The content that's causing the errors is under `content/examples` directory. 

The code and site work fine when run with the dev server, but not when the static site is generated.

**Comment by QingWei-Li** [comment]
After upgrading `nuxt` and `vue-markdown-loader` to the latest version, everything is fine.

```json
{
"dependencies": {
    "highlight.js": "^9.10.0",
    "nuxt": "^1.0.0-alpha.4",
    "sass-chunks": "0.0.2",
    "vuency": "0.0.95"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.15.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-config-vue": "^2.0.2",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1",
    "eslint-plugin-vue": "^2.0.1",
    "node-sass": "^4.5.2",
    "pug": "^2.0.0-beta.12",
    "push-dir": "^0.4.1",
    "sass-loader": "^6.0.3",
    "vue-markdown-loader": "^1.0.0"
  }
}
```

**Comment by alidcastano** [comment]
Thanks for taking the time to check out the error. 

I've tried it with both upgraded versions, I even pushed the most recent version.

If you run `npm run generate` and then try to serve the static site `serve dist/` you'll see that in those pages (e.g. http://localhost:5000/question-genie/) the component isn't rendering correctly and emits errors.

**Comment by QingWei-Li** [comment]
![image](https://user-images.githubusercontent.com/7565692/27110845-a6b056a8-50de-11e7-8b6f-75eafc388952.png)
No error.

Maybe you can try deleting the `node_modules` folder and then `npm install`.

**Comment by alidcastano** [comment]
Sorry, I'm an idiot – that's the only example that works, all the others (e.g. http://localhost:5000/coin-flip/ -- actually that one!) don't work.

<img width="1280" alt="screen shot 2017-06-13 at 10 36 23 pm" src="https://user-images.githubusercontent.com/11031952/27113074-c754d330-5088-11e7-8721-c14768199ccf.png">

That's what's weird. The coin flip example works, as shown in the picture you posted above. But it doesn't work in the other pages if any text follows the included component snippet. 

```
// This will work: 
<CoinFlip />

// This will not work:
<CoinFlip />
More Text here! 
```

**Comment by QingWei-Li** [comment]
Sorry i'm not familiar with `nuxt.js`. But when i removed `vue-markdown-loader`, only keep `CoinFlip` and `InfiniteAjax` pages, and the content write in `*.vue` file, Still the same error.

So it is impossible to `vue-markdown-loader` caused by the bug. Sorry I have no ability to solve, maybe you can ask nuxt team.

*InfiniteAjax.vue*

```vue
<template>
  <section>
    <h2>Infinite Ajaxff</h2>
    <p>ff</p>
    <div class="showcase">
      <InfiniteAjax/>
    </div>
    <h4>Script</h4>
    <h3>Template</h3>
  </section>
</template>

<script>
import InfiniteAjax from '~components/tasks/examples/InfiniteAjax.vue'

export default {
  components: {
    InfiniteAjax
  }
}
</script>
```

*CoinFlip.vue*

```vue
<template>
  <section>
    <h2>Coin Flip</h2>
    <div class="showcase">
      <CoinFlip />
    </div>
    <h3>Script</h3>
    <h3>Template</h3>
  </section>
</template>

<script>
import CoinFlip from '~components/tasks/examples/CoinFlip.vue'

export default {
  components: {
    CoinFlip
  }
}
</script>
```

![image](https://user-images.githubusercontent.com/7565692/27138486-25687a9c-5153-11e7-90ee-f7c6f5dbe475.png)

**Comment by alidcastano** [comment]
Okay, thanks again for going out of your way to try and fix the issue!
