### ISSUE TITLE
请问有考虑过支持多级目录的 markdown 文件么？

### ISSUE THREAD

**Issue by ppJuan** [QingWei-Li/vue-markdown-loader#25]
比如我有一个目录文件 `SUMMARY.md`
```
* [Introduction](README.md)
* [1. 燃料学](ch1/fuel.md)
* [2. 空气动力学](ch1/air.md)
* [3. 总装工程学](ch1/enginer.md)
```
最后生成的页面中点击该链接会提示 `Cannot GET /ch1/air.md`

**Comment by QingWei-Li** [comment]
这个跟 loader 有什么关系 😂

**Comment by ppJuan** [comment]
sorry 我也不知道这是不是 loader 该做的事…… markdown 中链接的其他 markdown 被解析为 `<a>` 标签，webpack 不会将下层 `.md` 文件打包，必须得手动添加前端路由

**Comment by QingWei-Li** [comment]
肯定只能手动去做了，或者自己写一个 markdown 的插件，这不是 loader 该做的事

**Comment by ppJuan** [comment]
好的，谢谢
