### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by metamn** [QingWei-Li/vue-markdown-loader#30]
Hello & thanks for the plugin !

I'm trying to add to my project but getting an error message:

```
ERROR in ./src/stories/README.md Module parse failed: /home/cs/work/vue/test1/src/stories/README.md Unexpected character '#' (1:0) You may need an appropriate loader to handle this file type. | # README | | @ ./src/stories/index.js 9:0-39 @ ./.storybook/config.js @ multi ./~/@storybook/vue/dist/server/config/polyfills.js ./~/@storybook/vue/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
```

Here is the webpack config file: https://github.com/metamn/vue/blob/master/test1/build/webpack.base.conf.js

And here is the code: https://github.com/metamn/vue/blob/master/test1/src/stories/index.js

Can you please advice me how to fix it? Thank you.

**Comment by QingWei-Li** [comment]
I think you shoud add your config in `.storybook/webpack.config.js`. See https://storybook.js.org/configurations/custom-webpack-config/#extend-mode

**Comment by metamn** [comment]
Oh, thanks, that was the case :+1:
