### ISSUE TITLE
在vue-cli中使用 一直报错 markdown文件加载不出来

### ISSUE THREAD

**Issue by zikuai** [QingWei-Li/vue-markdown-loader#36]
报错如下：Failed to mount component: template or render function not defined.

**Comment by everlose** [comment]
这个问题我遇到过。。webpack3会把似乎输出了个es6模块，如果你是require进来的话，仔细看下router require引用的时候动态引入问题，我现在是着么引入的。
```
component: r => require.ensure([], () => r(require('../docs/test.md')))
```

**Comment by zikuai** [comment]
后面修改vue-loader.conf中加上esModule: false
