### ISSUE TITLE
需要考虑兼容 vue-loader15 了

### ISSUE THREAD

**Issue by tianyong90** [QingWei-Li/vue-markdown-loader#42]
vue-loader15 目前已经进入 rc 版本阶段了，相信很快会正式发布，但目前 vue-markdown-loader 似乎并不兼容。

**Comment by zouyaoji** [comment]
今天升级了vue-loader15，发现vue-markdown-loader不兼容，又退vue-loader14了，会考虑兼容吗？

**Comment by tianyong90** [comment]
@zouyaoji 自己撸个 loader 也不难。我最后自己写了一个，其实也就是把 veupress 里的一部分提取出来了。
https://github.com/tianyong90/vue-markdown-loader

**Comment by zouyaoji** [comment]
@tianyong90 我试了你这个 还是报错。

**Comment by tianyong90** [comment]
我在我自己项目里用是没问题，自己项目里vue-loader 一直用的最新的（有点儿升级强迫症:smile:）

**Comment by zouyaoji** [comment]
算了 不折腾了
