### ISSUE TITLE
markdown-it config not worked

### ISSUE THREAD

**Issue by ideagay** [QingWei-Li/vue-markdown-loader#45]
## webpack.config.js

const hljs = require('highlight.js');
const markdown = require('markdown-it')({
  html: true,
  breaks: true,
  wrapper: 'section',
  preprocess: function (MarkdownIt, Source) {
    return Source;
  },
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return '<pre class="hljs"><code>' +
            hljs.highlight(lang, str, true).value +
            '</code></pre>';
      } catch (__) {}
    }
    return '<pre class="hljs"><code>' + markdown.utils.escapeHtml(str) + '</code></pre>';
  }
});
markdown.use(require('markdown-it-emoji'));

...{
        test: /\.md$/,
        loader: 'vue-markdown-loader',
        options: markdown
      }

but the wrapper was undefined  and the hightlight was not worked
![image](https://user-images.githubusercontent.com/4416844/40606337-a6e7383c-6297-11e8-85bb-f8f1bfc7b2b1.png)

**Comment by wxy1234567890** [comment]
markdown-it-emoji怎么在Vue CLI 3的vue.config.js file中配置
