### ISSUE TITLE
webpack 4 下，不能解析script

### ISSUE THREAD

**Issue by Lemenxzy** [QingWei-Li/vue-markdown-loader#48]
解析出来的.md没有 <script></script> 标签，为空

**Comment by Lemenxzy** [comment]
这将导致 解析出的组件 没有自定义的事件和data 报错

**Comment by Lemenxzy** [comment]
如果换成 vue-loader 15的话
webpack应该这样写

{
test: /\.md$/,
    use: [
        {
            loader: 'vue-loader'
        },
        {
            loader: 'vue-markdown-loader/lib/markdown-compiler',
            options: {
                raw: true
            }
        }
    ]
}

那么 vue-markdown-loader 的 options 怎么设置？？

大神求解答一下

**Comment by Lemenxzy** [comment]
看了源码明白了。

**Comment by samchen08** [comment]
求赐教

**Comment by Lemenxzy** [comment]
你想知道哪款，是关于option吗？

**Comment by weifu2** [comment]
markdown-it 的配置不生效了，可知道怎么解决？
![image](https://user-images.githubusercontent.com/31844035/44887409-bf8a9080-acfe-11e8-99c5-715025c36609.png)

![image](https://user-images.githubusercontent.com/31844035/44887396-b0a3de00-acfe-11e8-9d19-a760782eff7f.png)

上述 markdown 配置没用
