### ISSUE TITLE
组件如用emit方法，在md中使用该组件emit无效

### ISSUE THREAD

**Issue by Clark-Zhao** [QingWei-Li/vue-markdown-loader#5]
比如我有一个组件有个方法用到emit
```
  methods: {
    closeAside: function() {
      this.$emit('closeAside')
    }
  }
```
然后父组件
`@closeAside="xxx.show = false"`

我在vue中使用这个组件亲测是可以成功触发改变show值的，但是我把这个组件用在md文件中就没反应。

希望dalao有空帮忙解答一下

**Comment by QingWei-Li** [comment]
升级最新了么？

这问题我已经修复过了 https://github.com/QingWei-Li/vue-markdown-loader/blob/master/lib/core.js#L97-L100

**Comment by Clark-Zhao** [comment]
@QingWei-Li 是的，我的版本是0.5.1，这个版本号应该是最新的

**Comment by QingWei-Li** [comment]
可否提供个 demo？

**Comment by Clark-Zhao** [comment]
@QingWei-Li http://zhaoyuxiang.cn/vue-markdown-loader-emit-demo/

**Comment by QingWei-Li** [comment]
修复了，升级到 0.6.0

**Comment by Clark-Zhao** [comment]
0.6.0亲测可用，感谢大神
