### ISSUE TITLE
Use loader as template lang 

### ISSUE THREAD

**Issue by alidcastano** [QingWei-Li/vue-markdown-loader#6]
Would it be possible to use this loader as a template language instead?

For example: `<template lang="md"> # Cool! </template> `

The reason this is preferable is that most editors already support vue syntax highlighting, while they don't necessarily support javascript syntax highlighting inside .md files.

**Comment by QingWei-Li** [comment]
This feature may be supported in `vue-loader` https://github.com/vuejs/vue-loader/pull/499

**Comment by asselin** [comment]
Actually, I think that should work with the currently shipping version of vue-loader

**Comment by alidcastano** [comment]
@QingWei-Li  @asselin Great, I will make sure to give it another try soon. Thanks.

**Comment by alidcastano** [comment]
Recently had a chance to try it and wasn't able to get neither `lang="md"` or `lang="markdown` to work. 

I get a `Error: Template engine 'md' isn't available`. Is there anything specific I can to do to make it available for `.vue` file templates? I tried configuring under vue loader options but couldn't get it to work.

**Comment by asselin** [comment]
@alidcastano  Add `<template lang="md">`  in your .vue file, and then in the webpack configuration, add `vue.loaders.md = 'vue-markdown-loader'` (webpack 1.x).  Note that that will be slightly different if you're using webpack 2.x.

**Comment by levoLee** [comment]
how can I rewrite the html structure in .md file by using vue-markdown-loader?
