### ISSUE TITLE
docsify和vue-markdown-loader结合使用

### ISSUE THREAD

**Issue by Galen-Yip** [QingWei-Li/vue-markdown-loader#8]
如题，两者能合着用最好了
不是vuep那种编辑实时预览

**Comment by QingWei-Li** [comment]
想不到要如何结合.... 两者定位不同，有啥 idea 没

**Comment by QingWei-Li** [comment]
大概猜到你的需求了，是不是想要一个写文档的 webpack 项目模板？直接写 markdown 就可以编译出一个文档网站

**Comment by Galen-Yip** [comment]
哈对 其实就是用到docsify 但要支持vue 这样写md方便

**Comment by QingWei-Li** [comment]
过几天弄

**Comment by QingWei-Li** [comment]
突然想到你可以试试 vue-play 感觉能满你需求

**Comment by Galen-Yip** [comment]
哈哈你真上心

**Comment by Galen-Yip** [comment]
实现的话 有什么思路没

**Comment by QingWei-Li** [comment]
做的话估计也只是写个 vue + webpack，的项目模板，个人感觉意义不大 😂 可能不会做

**Comment by Galen-Yip** [comment]
不是呀 
vue-antd-docs-loader 这个是个vue loader的预处理插件 他还是写.vue
跟docsify结合的话 可以考虑下怎么改

**Comment by Galen-Yip** [comment]
@QingWei-Li 想了下感觉就是写个vue和webpack的demo....
额 也没很方便的方式去写

**Comment by QingWei-Li** [comment]
用 `vue build` 写一个 https://github.com/vuejs/vue-cli/blob/master/docs/build.md 🌚
