### ISSUE TITLE
不支持写简单的代码么

### ISSUE THREAD

**Issue by wulucxy** [QingWei-Li/vue-markdown-loader#9]
我现在的需求是需要对md和部分简单链接进行混排，类似于下面的方案：

```
## test
> some text

<a href="/home">打开首页</a>
```

结果是a标签直接被转化为文本格式，请问这个可以实现么

@QingWei-Li

**Comment by QingWei-Li** [comment]
支持的呀
```markdown

# Hello

`<span>{{sss}}</span>`

> This is test.

<a href="/home">打开首页</a>


- How are you?
- Fine, Thank you, and you?
- I'm fine， too. Thank you.
- 🌚
```
![image](https://cloud.githubusercontent.com/assets/7565692/22293146/72854eb8-e349-11e6-9913-27a9fe939bae.png)

**Comment by wulucxy** [comment]
@QingWei-Li 找到原因了，

如果a标签空space的空间，就默认转义为字符。

如果取消空格，就能默认展示html标签了。
